services:
  postgres:
    image: postgres:16
    container_name: postgres_livros
    environment:
      POSTGRES_DB: livros_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  apilivros:
    image: apilivros
    build:
      context: .
      dockerfile: ApiLivros/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=livros_dev;Username=postgres;Password=postgres;Port=5432

volumes:
  postgres_data:
