services:
  database:
    image: postgres:15
    container_name: livros-database
    environment:
      POSTGRES_DB: livros_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - livros-network

  backend:
    build:
      context: .
      dockerfile: ./ApiLivros/Dockerfile
    container_name: livros-backend
    ports:
      - "5000:8080"
    depends_on:
      - database
    networks:
      - livros-network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=database;Port=5432;Database=livros_db;Username=postgres;Password=postgres123

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: livros-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - livros-network

volumes:
  postgres_data:

networks:
  livros-network:
    driver: bridge
